version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      playwright:
        patterns:
          - "@playwright/*"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
